### ISSUE TITLE
Something Strange

### ISSUE THREAD

**Issue by mattCasanova** [jtsmith2/ynab-email#1]
Hello.  I am not too familiar with python so I might be doing something wrong.  When trying to run this using python3.5 (Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) ) i get this error.

File "ynabemail.py", line 90, in main
    bal_diff = balances[subs[cat+"_subs"][scat].id].balance - old_balances[subs[cat+"_subs"][scat].id].balance
AttributeError: 'int' object has no attribute 'balance'

I fixed it on my version by not accessing .balance from the old_balances dictionary.  I don't know if I am using an older version of python or if there is a problem with the code, so I thought I would let you know.

**Comment by mattCasanova** [comment]
The fix i made was changing line 90 to
bal_diff = balances[subs[cat+"_subs"][scat].id].balance - old_balances[subs[cat+"_subs"][scat].id]

**Comment by jtsmith2** [comment]
That fix will only fix the issue the first time you run the code.  After that you'll get an error because old_balances will be returning an object and balances.balance will be returning an int.  I've got a fix I'm uploading now to fix the behavior of the defaultdict I was using.

**Comment by jtsmith2** [comment]
Fixed in most recent commit.
